--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/HashBlameMojangAttribute
build-by-default: true
branches:
- master
projects:
  libBlameMojangAttribute:
    path: ""
    model: virion
    type: library
...
